# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  # - name: Home
  #   url: '#about'
  #   weight: 10
  # - name: Courses
  #   weight: 20
  #   identifier: courses
  # - name: Home
  #   url: '/'
  #   weight: 10

  - name: Documentation
    PageRef: docs/_index.md
    weight: 20
  - name: Paper
    url: https://openaccess.thecvf.com/content/CVPR2023/papers/Kulinski_StarCraftImage_A_Dataset_for_Prototyping_Spatial_Reasoning_Methods_for_Multi-Agent_CVPR_2023_paper.pdf
    weight: 30
  - name: Github
    url: https://github.com/inouye-lab/starcraftimage
    weight: 100

#  - name: Posts
#    url: '#posts'
#    weight: 20
#  - name: Projects
#    url: '#projects'
#    weight: 30
#  - name: Talks
#    url: '#talks'
#    weight: 40
#  - name: Publications
#    url: '#featured'
#    weight: 50
#  - name: Contact
#    url: '#contact'
#    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
